myapp/main/routes.py
#! /usr/bin/env python
from hashlib import blake2s
import os
import socket
import sys
import time
import threading
sys.path.append("./")
from myapp.main import kyber as Kyber
from myapp.main import dilithium as Dilithium
from base64 import b64encode, b64decode
import json
from Crypto.Cipher import ChaCha20
from hashlib import blake2b
import requests
from myapp.main import upnpcclient

receivedkyberpubkey = ""

from flask import (Blueprint, render_template, session, copy_current_request_context, 
                    request, redirect, url_for, flash)
from flask_socketio import emit
from myapp import socketio, db
from myapp.models import (User, Messages, MyIdentity, 
                            CurrentIdentity, Notifications, HostPort,
                            ReceivedPublic)
from werkzeug.utils import secure_filename
from flask import current_app


mylist = []

main = Blueprint('main', __name__)


@main.before_app_first_request
def start_server_first():
    current_identity = CurrentIdentity.query.first()
    if current_identity==None:
        print("current empty")
        myid = MyIdentity.query.first()
        if myid==None:
            print("myid empty")
            flash("There is no identity available. \
            Please make an identity first!", "danger")

    # try:
    #     if session['privatekey'] and session['publickey']:
    #         pass
    #         # flash("Client started.", "info")
    # except KeyError:
    #     create_keys()
        # flash("Client started.", "info")

    res = start_server()
    session['server started'] = True
    session.pop('current_client', None)
    print('Server started')


@main.route('/dropall')
def dropall():
    # db.session.rollback()
    db.drop_all()
    db.create_all()
    return redirect(url_for('main.home'))


@main.route('/amd')
def erase():
    return "Erased called"

@main.route('/')
def home():
    users = User.query.all()
    pr = HostPort.query.first()
    if pr==None:
        return "Restart the server from console!"
    else:
        host = pr.host
        port = pr.port_no

    current_identity = CurrentIdentity.query.first()

    if current_identity:
        myid = MyIdentity.query.get(current_identity.identity_no)
    else:
        myid = MyIdentity.query.first()
    allids = MyIdentity.query.all()

    notifications = Notifications.query.all()


    return render_template('new_layout.html', users=users, myhost=host, myport=port, 
                                    myid=myid, allids=allids, notifications=notifications)

@main.route('/change_profile', methods=['POST'])
def change_profile():
    id = request.json['id']

    # removing all id
    CurrentIdentity.query.delete()

    # adding new current id
    cid = CurrentIdentity(identity_no=id)
    db.session.add(cid)
    db.session.commit()

    return "done"



def create_keys():
    mykeys = Kyber.createkeys()
    privatekey = mykeys[0]
    publickey = mykeys[1]
    mydilkeys = Dilithium.createkeys()
    dilprivatekey = mydilkeys[0]
    dilpublickey = mydilkeys[1]



    myuser = {
        "Ki": privatekey,
        "Kp": publickey,
        "Di": dilprivatekey,
        "Dp": dilpublickey
    }

    return myuser

@main.route('/create_newid', methods=['POST'])
def create_newid():
    if request.method == "POST":
        profile_pic = request.files['profile_pic']
        username = request.form.get('username')
        keys = create_keys()
        private_key = keys["Ki"]
        public_key = keys["Kp"]
        dil_private_key = keys["Di"]
        dil_public_key = keys["Dp"]
        # unique_id = session['unique_id']

        filename = secure_filename(profile_pic.filename)
        if filename and filename is not None and filename != '':
            profile_pic.save(os.path.join('myapp/static/images', filename))
        else:
            filename = 'default.jpg'


        myid = MyIdentity(username=username, private_key=private_key, public_key=public_key,
                            dil_private_key=dil_private_key, dil_public_key=dil_public_key,
                            unique_id='none', profile_pic=filename)

        db.session.add(myid)
        db.session.commit()

        
        return redirect(url_for('main.home'))

    return "you have made a 'Get' request"



@main.route('/renewport')
def renewport():
    upnpcobject = upnpcclient.port_manager()
    upnpcobject.unmap_ports()
    port=upnpcobject.mapport()[1]
    print("Using port: "+ port)

    pr = HostPort.query.first()
    if pr==None:
        p = HostPort(port_no=port)
        db.session.add(p)
    # f = open('openport.txt', 'w')
    # f.write(str(port))
    # f.close()
    else:
        pr.port_no = port

    db.session.commit()
    return {'port': port}

# New conversation
@main.route('/server')
def start_server():
    pr = HostPort.query.first()
    if pr==None:
        port=renewport()['port']
    else:
        port = pr.port_no

    @copy_current_request_context
    def startServer():
        req = requests.get("https://checkip.amazonaws.com/", 'html.parser').text
        print("Your external IP is: "+ req)

        sock=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
        print("Server started successfully\n")
        hostname=''

        try:
            sock.bind((hostname, port ))
        except:
            renewport()
            return redirect(url_for('main.start_server'))

        # session['myport'] = port
        sock.listen(1)
        print("Listening on port %d\n" % port)        
        #time.sleep(2)    
        (clientname,address)=sock.accept()
        print("Connection from %s\n" % str(address))

        # getting keys from currentidentity
        current_identity = CurrentIdentity.query.first()
        if current_identity:
            myid = MyIdentity.query.get(current_identity.identity_no)
        else:
            myid = MyIdentity.query.first()

        hashofpub = str(blake2s((myid.public_key + myid.dil_public_key).encode()).hexdigest())
        print("My Kyber+Dilithium hash: "+hashofpub)
        session['unique_id'] = hashofpub
        print('unique id below: ')
        print(session['unique_id'])

        counter = 0
        messagelist = []
        decapsulatedkey = ""

        pubkeycounter = 0
        pubkeysignal = False
        receivedkyberpubkey = ""

        ctkeycounter = 0
        ctsignal = False
        receivedctkey = ""

        chachacounter = 0
        chachasignal = False
        chachadata = ""

        while 1:
            chunk=clientname.recv(4096)            
            #print(str(address)+':'+chunk.decode(encoding="utf-8"))
            messagelist.append(chunk.decode(encoding="utf-8"))

            
            if (pubkeycounter > 0 or pubkeysignal == True):
                receivedkyberpubkey = messagelist[ctkeycounter+1]
                print("Received public key:"+receivedkyberpubkey)
                hashofpub = str(blake2s(receivedkyberpubkey.encode()).hexdigest())
                print("Hash of public key:"+hashofpub)
                ReceivedPublic.query.delete()
                received_public = ReceivedPublic(key=receivedkyberpubkey)
                db.session.add(received_public)
                db.session.commit()
                # f = open('received.public', 'w')
                # f.write(receivedkyberpubkey)
                # f.close()


                pubkeycounter = 0
                pubkeysignal = False

            if( "==PUBKEY==" in messagelist[counter] ):
                pubkeycounter = counter
                pubkeysignal = True

            if (ctkeycounter > 0 or ctsignal == True):
                #Process KEM key
                receivedctkey = messagelist[ctkeycounter+1]
                #print("KEM key:"+receivedctkey)
                hashofkem = str(blake2s(receivedctkey.encode()).hexdigest())
                #print("HASH of KEM: "+ hashofkem)
                decapsulatedkey = Kyber.decapsulate(receivedctkey, myid.private_key)
                #print("DECAPSULATED KEY:"+decapsulatedkey)
                ctkeycounter = 0
                ctsignal = False
            if( "==KEM-KEY-INIT==" in messagelist[counter] ):
                ctkeycounter = counter
                ctsignal = True
                    #print("KEM detected: "+ str(ctkeycounter))

            
            if (chachacounter > 0 or chachasignal == True):
                #Process CHACHADATA
                chachadata = messagelist[chachacounter+1]
                #print("CHACHA Data:"+str(chachadata))
                b64 = json.loads(chachadata)
                nonce = b64decode(b64['nonce'])
                ciphertext = b64decode(b64['ciphertext'])
                chachakey = bytes( blake2b( decapsulatedkey.encode(),digest_size=16 ).hexdigest(), "utf-8")
                #print("CHACHAKEY:"+str(chachakey))
                cipher = ChaCha20.new(key=chachakey, nonce=nonce)
                plaintext = cipher.decrypt(ciphertext)
                
                # Printing and sending client message
                new_message = str(plaintext, "utf-8")
                print(str(address)+':'+ new_message)

                msg = new_message.split(',')
                client_host = msg[0].split(':')[0]
                client_port = msg[0].split(':')[1]
                message = msg[1]
                message = {'host': client_host, 'port': client_port, 'message': message}
                socketio.emit('new_message', message, json=True)

                print(req.strip('\n'))
                if client_host == req.strip('\n'):
                    client_host = ''
                print(client_host == req.strip('\n'))

                messg = 'client: ' + str(msg[1])

myapp/templates/modals/connect_modal.html
<!-- Modal -->
<div class="modal fade" id="connectModal" tabindex="-1" role="dialog" aria-labelledby="connectModalLabel" aria-hidden="true">
	<div class="modal-dialog-centered modal-dialog" role="document" style="margin-left: -20%;">
	  <div class="modal-content">

		
		<div class="modal-body text-center">
            <button type="button" class="close display-inline-block" data-dismiss="modal" aria-label="Close"
            style="transform: scale(2,2);">
                <span aria-hidden="true">&times;</span>
              </button>
            <div class="connect_box">
                <span class="font-weight-bold" id="exampleModalLongTitle" style="font-size: xx-large;">Connect to Client</span>

                <input type="text" id="host" class="profile_name mt-2" placeholder="111.555.888.04">

                <input type="text" id="port" class="profile_name mt-2" placeholder="80">

                <input type="text" id="uname" class="profile_name mt-3" placeholder="Enter client name(optional)" name="username">
            
                <button id="connectBtn" class="btn btn-lg mt-2 font-weight-bold" style="background-color: #dacb58; color:white;">
                Connect Now</button>
            </div>
		</div>

		
	  </div>
	</div>
  </div>

<style>

.connect_box{
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 10px;
}

</style>

<script src="{{ url_for('static', filename='js/new_layout/connect_modal.js') }}"></script>

myapp/templates/modals/keys_modal.html
<!-- Modal -->
<div class="modal fade" id="keysModal" tabindex="-1" role="dialog" aria-labelledby="keysModalLabel" aria-hidden="true">
	<div class="modal-dialog-centered modal-dialog" role="document" style="margin-left: -20%;">
	  <div class="modal-content" style="width:800px;">

        <div class="modal-header" id="modal-header">
            <!-- close button -->
            <button type="button" class="close display-inline-block" data-dismiss="modal" aria-label="Close" style="transform: scale(2,2);">
                <span aria-hidden="true">&times;</span>
            </button>
          </div>


            <div class="btn-group" style="margin: auto;">
                <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="login-status mx-auto">
                        <div>
                        <img src="{{ url_for('static', filename='images/') }}{{myid.profile_pic}}" alt="profile pic"
                            class="profile_pic">
                        </div>
        
                        <div>
                            <h2 class="p-1">Logged In as {{ myid.username }}</h2>
                            <p class="p-1">using ip port <span class="font-weight-bold">{{myhost}}:{{myport}}</span></p>
                        </div>
                    </div>
                </button>
                <div class="dropdown-menu dropdown_links">
                    {% for id in allids %}
                        <div class="m-1 d-flex p-2" onclick="changeProfile({{id.id}})">
                            <img src="{{ url_for('static', filename='images/') }}{{id.profile_pic}}" 
                            alt="profile image" style="width: 40px; height: 30px; border-radius: 30px;" />
                            <a class="dropdown-item" href="#">{{ id.username }}</a>
                            {% if myid.username == id.username %}
                                <span class="green-dot">
                                    <i class="bi bi-check" 
                                    style="color: honeydew; font-size: 1.5rem;">
                                </i></span>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
              </div>

          
		<!-- keys modal 1-->
		<div class="modal-body text-center" id="keys_modal_1">

            <!-- private key -->
            <div class="p-section">
                <div>
                    <span class="p-text">Private Key:</span>
                    <span class="copy">Copy</span>
                </div>
                <div>
                        <p class="p-key">{{ myid.private_key }}</p>
                </div>
            </div>

            <!-- public key -->
            <div class="p-section">
                <div>
                    <span class="p-text">Public Key:</span>
                    <span class="copy">Copy</span>
                </div>
                <div>
                        <p class="p-key">{{ myid.public_key }}</p>
                </div>
            </div>
            <button id="newIdButton" class="btn btn-lg" style="background-color: #dacb58; color:white;">
                Create new identity</button>
		</div>




        <!-- create keys block 2-->
        <div class="modal-body" id="keys_modal_2" style="display: none;">
            <button class="btn text-left" id="backBtn"> < Back</button>

            <h2 class="hd2">Create new identity</h2>
            <p class="unique-id">Your unique id: 24df5455ffasdf58r256asd3f2f5asd6f5fa6sdf</p>

            <form action="{{ url_for('main.create_newid') }}" method="POST" enctype="multipart/form-data">
                <div class="file_div text-center">
                    <div class="image-upload">
                        <label for="file-input">
                            <i class="bi bi-person-plus-fill file_image"></i> <span>Upload Your Profile Picture</span>
                        </label>
                    
                        <input id="file-input" type="file" name="profile_pic" />
                    </div>

                    <input type="text" class="profile_name" name="username" placeholder="Enter your name">

                    <button class="createBtn" style="background-color: #dacb58; color: white;
                    margin-top: 20px; padding: 8px 18px; border: none; border-radius: 5px; font-weight: bold;">
                    Create</button>
                </div>
            </form>
		</div>

		
	  </div>
	</div>
  </div>

<style>

#modal-header{
    display: flex;
    flex-direction: column;
    align-items: center;
}



.login-status{
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    align-self: center;
    border: 1px solid black;
    border-radius: 5px;
    padding: 5px;
}

.dropdown_links{
    width: 300px;
    height: auto;
    margin: auto;
}

.green-dot{
    width: 30px;
    height: 23px;
    background-color: green;
    border-radius: 50%;
    margin-right: 10px;
}

.p-section{
    display: flex;
    flex-direction: column;
    margin-bottom: 15px;
}

.p-text{
    float: left;
    margin: 5px 0px;
}
.copy{
    float: right;
    margin: 5px 0px;
}
.p-key{
    padding: 10px;
    border: 1px solid rgb(189, 185, 185);
    border-radius: 5px;
    overflow-wrap: break-word;
}

/* modal 2 */
#keys_modal_2{
    display: flex;
    flex-direction: column;
    align-self: center;
    align-items: center;
    justify-content: center;
}

.hd2{
   font-size: 25px;
   text-align: center;
   font-weight: bolder;

}

.unique-id{
    margin: 20px 0px;
    text-align: center;
    text-overflow: clip;
}

.profile_name{
    display: block;
    margin: auto;
    padding: 10px;
    width: 400px;
    height: 50px;
    border-radius: 15px;
    border: 1px solid rgb(209, 206, 206);


}
.file_image{
    font-size: 2rem;
    border: 1px solid rgb(209, 206, 206);
    padding: 12px 15px 12px 20px;
    border-radius: 55%;
    margin-right: 20px;
    margin-top: 40px;
    margin-bottom: 40px;

}

/* file upload css */
.image-upload > input
{
    display: none;
}

.image-upload img
{
    width: 80px;
    cursor: pointer;
}
.image-upload{
    cursor: crosshair;
    margin-top: 40px;
    margin-bottom: 35px;
}

</style>

<script type="text/javascript">

    let keys_1 = document.getElementById("keys_modal_1");
    let keys_2 = document.getElementById("keys_modal_2");
    let modal_header = document.getElementById("modal-header");

    let newIdButton = document.getElementById("newIdButton");
    let backBtn = document.getElementById("backBtn");

    newIdButton.addEventListener('click', showCreateKeys);
    backBtn.addEventListener('click', showKeysModal);

    // functions for showing create keys modal
    function showCreateKeys(){
        keys_1.style.display = 'none';
        modal_header.style.display = 'none';
        keys_2.style.display = 'block';
    };

    // function for removing create keys and showing keys modal
    function showKeysModal(){
        keys_1.style.display = 'block';
        modal_header.style.display = 'flex';
        keys_2.style.display = 'none';
    }


function changeProfile(id){
    console.log(id);

    const chId = new XMLHttpRequest();

    chId.open('post', '/change_profile', true);
    chId.setRequestHeader("Content-Type", "application/json");

    let data = {'id': id};

    chId.send(JSON.stringify(data))

    chId.onload = function(){
        if(this.responseText == "done"){
            window.location.href = '/';
        }
    };
};

</script>

myapp/templates/modals/ports_modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog-centered modal-dialog" role="document" style="margin-left: -20%;">
	  <div class="modal-content">

		
		<div class="modal-body text-center">
            <button type="button" class="close display-inline-block" data-dismiss="modal" aria-label="Close" style="transform: scale(2,2);">
                <span aria-hidden="true">&times;</span>
              </button>
            <span class="" id="exampleModalLongTitle" style="font-size: xx-large;">Port Settings</span>
          <p class="mt15">You are using port no: <span><b id="mynewport">{{myport}}</b></span></p>
          <p class="mt15">If there is no port available then <i>Renew it</i></p>
            <button id="renewPort" class="btn btn-lg" style="background-color: #dacb58; color:white;">
                Renew</button>
		</div>
		
	  </div>
	</div>
  </div>

<style>
.mt15{
    margin-top: 15px;
}
#renewPort{
    margin-top: 20px;
}
</style>

<script src="{{ url_for('static', filename='js/new_layout/renew_port.js') }}"></script>