myapp/conversation/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, session, flash
from myapp.models import User, Messages, Notifications
from myapp import db
import requests
import json

conversation = Blueprint('conversation', __name__)

@conversation.route('/connect', methods=['GET', 'POST'])
def connect():
    req = requests.get("https://checkip.amazonaws.com/", 'html.parser').text.strip('\n')
    print(req)

    
    if request.method == 'GET':
        username = request.args.get('username')
        host = request.args.get('host')
        port = request.args.get('port')
    elif request.method == 'POST':
        username = request.json['username']
        host = request.json['host']
        port = request.json['port']
    if req == str(host):
        host = ''
    user = User.query.filter(User.ip==host).filter(User.port==port).first()
    print(username)
    print(host)
    print(port)
    if user:
        print(f"user ip is: {user.ip}, port: {user.port}")
        if user.ip == host and user.port == port:
            return f"{user.id}"
            return redirect(url_for('main.chat', id=user.id))

    # if new chat

    # register it to database first
    newuser = User(username=username, ip=host, port=port)
    db.session.add(newuser)
    db.session.commit()

    # redirect to /chat with user.id
    get_newuser = User.query.filter_by(ip=host, port=port).first()
    if get_newuser:
        return f"{get_newuser.id}"

    return "Error"


@conversation.route('/get_messages/<string:userid>')
def get_messages(userid):
    messages = Messages.query.filter_by(user_id=userid).all()
    # print(messages[0].message)
    # print([i.message for i in messages])

    if messages:
        messages = [i.message for i in messages]
    else:
        messages = []
    user = User.query.get(userid)
    client_pic = user.profile_image
    host = user.ip
    port = user.port

    # reurning a list of messages into a dictionary
    return {'client_pic': client_pic, 'messages':  messages, 'host': host, 'port': port}
    


@conversation.route('/save_message', methods=['POST'])
def save_message():
    mess = request.json['message']
    user_id = request.json['user_id']
    if user_id==None:
        host = session['host']
        port = session['port']
        user = User.query.filter(User.ip == host).filter(User.port == port).first()
        user_id = user.id
    message = Messages(message=mess, user_id=user_id)
    db.session.add(message)
    try:
        db.session.commit()
    except:
        return "not added"
    return "added"

@conversation.route('/save_notification', methods=['POST'])
def save_notification():
    id = request.json['id']

    notification = Notifications(has_new_messages=True, user_id=id)
    db.session.add(notification)
    db.session.commit()

    return f"{id}"

@conversation.route('/remove_notification', methods=['POST'])
def remove_notification():
    id = request.json['id']
    print(id)
    allnotif = Notifications.query.all()
    for i in allnotif:
        print(i.user_id)
        print(i.user_id==None)
        if i.user_id == None:
            db.session.delete(i)
            # print(f"deleted: {i.ip}:{i.port}")
        db.session.commit()


    notification = Notifications.query.filter_by(user_id=id).first()
    print(f"notification: {notification}")
    if notification:
        db.session.delete(notification)
    db.session.commit()

    return "deleted"




@conversation.route('/delete_user/<int:id>')
def delete_user(id):
    user = User.query.get(id)
    if user:
        messages = Messages.query.filter_by(user_id=user.id).all()
        print(messages)
        [db.session.delete(i) for i in messages]
        db.session.delete(user)
        
        notification = Notifications.query.filter_by(user_id=id).first()
        if notification:
            db.session.delete(notification)
        db.session.commit()
        flash("User deleted successfully", "success")
    
    return "user deleted"

myapp/templates/_flash_message.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <ul class=flashes>
        {% for category, message in messages %}
            <li class="alert alert-{{ category }}">{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
{% endwith %}

myapp/templates/_navbar.html
  <link rel='stylesheet' href="{{ url_for('static', filename='css/fontawesome/css/all.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/nav_style.css') }}">
<!-- partial:index.partial.html -->
<nav class="sidebar-navigation display-block">
	<ul>
		<li class="mylist">
			<a href="{{ url_for('main.home') }}"
			style="color: white;">
			<i class="fa fa-home" id="{{ home }}"></i></a>
			<span class="tooltip">Home</span>
		</li>

		<!--   <li class="mylist">
			<i class="fas fa-coins"></i>
			<span class="tooltip">Register</span>
		</li>
		<li class="mylist">
			<i class="fa fa-user-circle"></i>
			<span class="tooltip">Login</span>
		</li>
		<li class="mylist">
			<a href="{{ url_for('main.connect_to_client') }}"><i class="fas fa-comments"></i></a>
			<span class="tooltip">Conversations</span>
		</li>  -->

		<li class="mylist">
			<a href="{{ url_for('main.settings') }}"
			style="color: white;">
			<i class="fas fa-cog" id="{{ settings }}"></i></a>
			<span class="tooltip">Settings</span>
		</li>
	</ul>
</nav>
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

myapp/templates/index.html
{% extends "layout.html" %}

{% block body %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

<div id="main">

<div class="button">
    <!-- plus button -->
        <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" id="plus">
        +
    </button>
    
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Connect to client</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <form method="POST">
            <div class="modal-body">
                
                <table class="table text-center table-dark">
                    <tr>
                        <td>ip: </td>
                        <td><input type="text" name="ip" id="ip" placeholder="111.555.888.04"></td>
                    </tr>
                    <tr>
                        <td>port: </td>
                        <td><input type="text" name="port" id="port" placeholder="80"></td>
                    </tr>
                </table>

                
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" id="connectbtn" 
            formaction="{{ url_for('conversation.connect') }}">
                Connect Now</button>
            </div>
        </form>
        </div>
        </div>
    </div>
</div>
<span id="myhost">{{host}}</span><span id="myport">{{port}}</span>
<!-- users chat list -->
<div id="chat-div" class="col-md-7 col-sm-7 col-lg-8">
    
    <table class="table table-sm table-striped">
        {% for user in users %}
            <tr>
                <td class="img-box"><img src="{{ url_for('static', filename='images/') }}{{ user.profile_image }}" 
                    alt="" class="profile-image">
                </td>
                <td class="align-middle">
                    <p><b><a href="{{ url_for('main.chat', id=user.id) }}">
                 {% if user.username %}
                    {{ user.username }}
                {% else %}
                    {{ user.ip }}:{{ user.port }}
                {% endif %}
                </a></b></p>
                </td>
                <td class="align-middle date-box">{{ user.last_seen.strftime('%A-%m-%Y') }}</td>
                <td><a href="{{ url_for('conversation.delete_user', id=user.id) }}" class="btn btn-danger">Delete</a></td>
            </tr>
        {% endfor %}
    </table>

</div>


</div>

<script src="{{ url_for('static', filename='js/ajax/index.js') }}"></script>
{% endblock body %}

myapp/templates/new_layout.html
<!DOCTYPE html>
<html class=''>
<head>
<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300' rel='stylesheet' type='text/css'>


<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


<script src="https://use.typekit.net/hoy3lrg.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css'>
<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css'>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">

<!-- script for making dialog box -->
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/blitzer/jquery-ui.css" type="text/css" />
<script src="{{ url_for('static', filename='js/new_layout/easy_confirm.js') }}"></script>
</head>
<body>


{% include "sections/_flash_alert_message.html" %}

<div id="frame">

    <div class="top-bar">
		<img src="{{ url_for('static', filename='images/Logo_gold.png') }}" alt="Beechat Logo"
		id="logo" onclick="window.location.href='/'">
		
				<div class="right-icons">
					{% if notifications %}
					
					<div class="notification_icon">
						<div class="btn-group">
							<button type="button" class="btn dropdown-toggle btn-dark" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="bi bi-chat-quote-fill" style="color: white; margin-right: 10px; transform: scale(1.5, 1.5);"></i>
							</button>
							<div class="dropdown-menu drop_menu" >
								{% for notification in notifications %}
								<a class="dropdown-item" data-toggle="modal">
								{% if notification.user_notification.username %}
								<span onclick="connectUser({{notification.user_id}})" class="n_{{notification.user_id}}">{{notification.user_notification.username}}</span>
								{% else %}
									<span onclick="connectUser({{notification.user_id}})" class="n_{{notification.user_id}}">{{notification.user_notification.ip}}:{{notification.user_notification.port}}</span>
								{% endif %}
								
								</a>
							{% endfor %}
							</div>
						</div>
						</div>
					{% else %}
					<div class="notification_icon">
						<div class="btn-group">
							<button type="button" class="btn dropdown-toggle btn-dark" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="bi bi-chat-fill" style="color: white; margin-right: 10px; transform: scale(1.5, 1.5);"></i>
							</button>
							<div class="dropdown-menu drop_menu">
							</div>
						</div>
						</div>
					{% endif %}
					
					
					<div class="setting_icon">
					<div class="btn-group">
						<button type="button" class="btn dropdown-toggle btn-dark" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="bi bi-gear-fill" style="color: white; transform: scale(1.3, 1.3);"></i>
						</button>
						<div class="dropdown-menu">
							<!-- This ports link is opening a modal from ports_modal.html -->
						<a class="dropdown-item" data-toggle="modal" data-target="#exampleModal">Ports</a>
						<!-- This Keys link is opening a modal from keys_modal.html -->
						<a class="dropdown-item" data-toggle="modal" data-target="#keysModal">Keys</a>
						</div>
					</div>
					</div>

					<span class="my-account-name">{{ myid.username }}</span>
					<span class="d-none"><span id="myhost">{{myhost}}</span><span id="myport">{{myport}}</span></span>
					<img src="{{ url_for('static', filename='images/') }}{{myid.profile_pic}}" alt="profile pic"
					class="profile_pic">
				</div> 
	</div>

	{% include "modals/ports_modal.html" %}
	{% include "modals/keys_modal.html" %}
	{% include "modals/connect_modal.html" %}

	{% include "sections/sidepanel_clients.html"  %}

	{% include "sections/contents.html"  %}
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.1.2/socket.io.js" integrity="sha512-iZIBSs+gDyTH0ZhUem9eQ1t4DcEn2B9lHxfRMeGQhyNdSUz+rb+5A3ummX6DQTOIs1XK0gOteOg/LPtSo9VJ+w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!-- socket messages receving script. redirecting client and connection. -->
<script src="{{ url_for('static', filename='js/ajax/client.js') }}"></script>


<script>

	window.onload = function() {
            let reloading = sessionStorage.getItem("click_li");
			let client_id = sessionStorage.getItem("client_id");
            console.log("window load function is" + reloading);
            if (reloading) {
                sessionStorage.removeItem("click_li");
				sessionStorage.removeItem("client_id");
                
				loadMessages(client_id);
				console.log("client id from page reloading: " + client_id)
				
            }else{
                console.log("session not available")
				sessionStorage.clear();
            }
        }
	
</script>

</body>
</html>